# Generated by Django 4.2.11 on 2024-06-02 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_orderposition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
    ]
