# Generated by Django 4.2.11 on 2024-06-02 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0006_product_units_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderposition',
            name='sum',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
