# Generated by Django 4.2.11 on 2024-06-02 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0008_order_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='sum',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
